import { useEffect, useMemo, useState } from 'react'
import './App.css'
import { missions as fallbackMissions, type Mission, type Level } from './data'
import type { MewayAuthResult } from './discord'

type Page = 'Главная'|'Миссии'|'Игры'|'Квизы'|'Слова'|'Челленджи'|'Награды'|'Профиль'|'Админ'
type Props = { discordAuth: MewayAuthResult; authReady: boolean }
const nav: Array<[string, Page]> = [['🏠','Главная'],['🎯','Миссии'],['🎮','Игры'],['📝','Квизы'],['📚','Слова'],['🔥','Челленджи'],['🏆','Награды'],['👤','Профиль']]
const levels = [{xp:500,icon:'🌱',name:'BEGINNER'},{xp:1000,icon:'📚',name:'LEARNER'},{xp:2000,icon:'🔥',name:'ACTIVE LEARNER'},{xp:3000,icon:'⭐',name:'ENGLISH EXPLORER'},{xp:5000,icon:'👑',name:'ENGLISH MASTER'},{xp:10000,icon:'💎',name:'MASTER ZONE'}]

function App({ discordAuth, authReady }: Props) {
  const [page,setPage] = useState<Page>('Главная')
  const [missions,setMissions] = useState<Mission[]>(fallbackMissions.filter(m=>m.status==='published'))
  const [selected,setSelected] = useState<Mission|null>(null)
  const [xp,setXp] = useState(()=>Number(localStorage.getItem('meway_xp')||120))
  const [nickname,setNickname] = useState(()=>localStorage.getItem('meway_nickname')||'Путешественник')
  const [completed,setCompleted] = useState<number[]>(()=>JSON.parse(localStorage.getItem('meway_completed_missions')||'[]'))

  useEffect(()=>{ fetch('/api/missions').then(r=>r.json()).then(d=>d.ok&&setMissions(d.missions)).catch(()=>{}) },[])
  useEffect(()=>localStorage.setItem('meway_xp',String(xp)),[xp])
  useEffect(()=>localStorage.setItem('meway_nickname',nickname),[nickname])
  useEffect(()=>localStorage.setItem('meway_completed_missions',JSON.stringify(completed)),[completed])

  const name = discordAuth.user?.globalName || discordAuth.user?.username || nickname
  const current = [...levels].reverse().find(l=>xp>=l.xp) || levels[0]
  const next = levels.find(l=>xp<l.xp) || levels.at(-1)!
  const open=(p:Page)=>{setSelected(null);setPage(p)}

  return <div className="appShell">
    <aside className="sidebar">
      <button className="brand" onClick={()=>open('Главная')}><span>✈</span><b>MEWAY<small>Your way to English</small></b></button>
      <nav>{nav.map(([icon,label])=><button key={label} className={page===label&&!selected?'active':''} onClick={()=>open(label)}><i>{icon}</i>{label}</button>)}
        {discordAuth.authenticated&&discordAuth.role==='admin'&&<button className={page==='Админ'?'active adminNav':''} onClick={()=>open('Админ')}><i>⚙️</i>Админ</button>}
      </nav>
      <div className="sideProgress"><b>{current.icon} {current.name}</b><small>{xp} / {next.xp} XP</small><div><span style={{width:`${Math.min(100,xp/next.xp*100)}%`}}/></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><small>{page==='Главная'?'Добро пожаловать в MEWAY ✈️':'MEWAY · твой путь к английскому'}</small><h1>{selected?selected.title:page}</h1></div><div className="topUser"><b>⚡ {xp} XP</b><span>{name.charAt(0).toUpperCase()}</span></div></header>
      {!authReady&&discordAuth.connected&&<div className="notice">Подключаем Discord…</div>}
      {authReady&&discordAuth.connected&&!discordAuth.authenticated&&<div className="notice error">Discord не удалось подключить: {discordAuth.error} Закрой Activity и открой её снова после проверки настроек Cloudflare.</div>}
      {selected?<MissionPlayer mission={selected} done={completed.includes(selected.id)} onBack={()=>setSelected(null)} onComplete={()=>{if(!completed.includes(selected.id)){setCompleted([...completed,selected.id]);setXp(xp+selected.xp)}}}/>:page==='Главная'?<Home name={name} xp={xp} missions={missions} openMission={setSelected} open={open}/>:page==='Миссии'?<Missions missions={missions} completed={completed} openMission={setSelected}/>:page==='Профиль'?<Profile name={name} nickname={nickname} setNickname={setNickname} xp={xp} completed={completed.length} auth={discordAuth}/>:page==='Админ'&&discordAuth.role==='admin'?<Admin auth={discordAuth}/>:<Feature page={page}/>} 
    </main>
  </div>
}

function Home({name,xp,missions,openMission,open}:{name:string;xp:number;missions:Mission[];openMission:(m:Mission)=>void;open:(p:Page)=>void}){
  return <><section className="hero"><div><span className="eyebrow">ТВОЁ ПРИКЛЮЧЕНИЕ НАЧИНАЕТСЯ</span><h2>Привет, {name}!<br/><em>English starts here.</em></h2><p>Миссии, квизы, слова и челленджи в одном месте. Учись понемногу каждый день и открывай новые уровни MEWAY.</p><div className="heroActions"><button onClick={()=>missions[0]&&openMission(missions[0])}>Начать миссию →</button><button className="ghost" onClick={()=>open('Миссии')}>Все миссии</button></div></div><div className="plane">✈️<span>+XP</span></div></section>
  <section className="stats"><article><small>⚡ Твой XP</small><b>{xp}</b></article><article><small>🎯 Доступно миссий</small><b>{missions.length}</b></article><article><small>🌱 Следующая цель</small><b>{levels.find(l=>xp<l.xp)?.name||'MASTER ZONE'}</b></article></section>
  <div className="sectionTitle"><div><span>РЕКОМЕНДУЕМ</span><h3>Продолжай путешествие</h3></div><button onClick={()=>open('Миссии')}>Смотреть все →</button></div><section className="cards">{missions.slice(0,3).map(m=><MissionCard key={m.id} m={m} onClick={()=>openMission(m)}/>)}</section></>
}

function MissionCard({m,onClick}:{m:Mission;onClick:()=>void}){return <article className="missionCard" onClick={onClick}><div className="missionIcon">{m.icon}</div><div className="chips"><span>{m.level}</span><span>{m.category}</span></div><h3>{m.title}</h3><p>{m.description}</p><footer><small>⏱ {m.duration}</small><b>+{m.xp} XP</b></footer></article>}
function Missions({missions,completed,openMission}:{missions:Mission[];completed:number[];openMission:(m:Mission)=>void}){const [level,setLevel]=useState('Все');const shown=level==='Все'?missions:missions.filter(m=>m.level===level);return <><div className="pageIntro"><span>🎯 УЧЕБНЫЙ МАРШРУТ</span><h2>Выбери следующую миссию</h2><p>Проходи задания в своём темпе и получай XP за завершённые миссии.</p></div><div className="filters">{['Все','A1','A2','B1','B2','C1','C2'].map(x=><button className={level===x?'active':''} onClick={()=>setLevel(x)} key={x}>{x}</button>)}</div><section className="cards">{shown.map(m=><div className="cardWrap" key={m.id}>{completed.includes(m.id)&&<span className="done">✓ Выполнено</span>}<MissionCard m={m} onClick={()=>openMission(m)}/></div>)}</section></>}

function MissionPlayer({mission,done,onBack,onComplete}:{mission:Mission;done:boolean;onBack:()=>void;onComplete:()=>void}){const [i,setI]=useState(0);const [answer,setAnswer]=useState('');const [checked,setChecked]=useState(false);const [score,setScore]=useState(0);const task=mission.tasks[i];if(!task)return <section className="empty"><b>{mission.icon}</b><h2>{mission.title}</h2><p>В этой миссии пока нет заданий.</p><button onClick={onBack}>Назад</button></section>;const correct=answer===task.correctAnswer;const next=()=>{if(correct)setScore(score+1);if(i===mission.tasks.length-1){onComplete();setI(mission.tasks.length)}else{setI(i+1);setAnswer('');setChecked(false)}};if(i>=mission.tasks.length)return <section className="result"><div>🏆</div><span>МИССИЯ ЗАВЕРШЕНА</span><h2>Отличная работа!</h2><p>Результат: {score + (correct?1:0)} из {mission.tasks.length}. {done?'Миссия уже была пройдена.':`Начислено +${mission.xp} XP.`}</p><button onClick={onBack}>К миссиям</button></section>;return <section className="player"><button className="back" onClick={onBack}>← Назад</button><div className="playerHead"><span>{mission.icon}</span><div><small>{mission.level} · {mission.category}</small><h2>{mission.title}</h2></div><b>{i+1}/{mission.tasks.length}</b></div><div className="progress"><span style={{width:`${(i+1)/mission.tasks.length*100}%`}}/></div><article className="question"><span>ВОПРОС {i+1}</span><h3>{task.question}</h3><div className="answers">{task.options.map(o=><button disabled={checked} className={`${answer===o?'selected':''} ${checked&&o===task.correctAnswer?'correct':''} ${checked&&answer===o&&o!==task.correctAnswer?'wrong':''}`} onClick={()=>setAnswer(o)} key={o}>{o}</button>)}</div>{checked&&<div className={correct?'explain good':'explain'}><b>{correct?'✓ Правильно':'✕ Пока неверно'}</b><p>{task.explanation}</p></div>}<button className="primary" disabled={!answer} onClick={()=>checked?next():setChecked(true)}>{checked?(i===mission.tasks.length-1?'Завершить':'Следующий вопрос →'):'Проверить'}</button></article></section>}

function Feature({page}:{page:Page}){const map:Record<string,[string,string,string]>= {'Игры':['🎮','Игровая зона','Короткие игры для тренировки английского.'],'Квизы':['📝','Квизы','Быстрые проверки знаний по уровням A1–C2.'],'Слова':['📚','Словарь MEWAY','Сохраняй и повторяй новые английские слова.'],'Челленджи':['🔥','Челленджи','Ежедневные задания для серии обучения.'],'Награды':['🏆','Награды','Достижения и награды за твой прогресс.']};const x=map[page]||['✨',page,'Раздел MEWAY'];return <section className="empty"><b>{x[0]}</b><span>MEWAY</span><h2>{x[1]}</h2><p>{x[2]}</p><div className="coming">Раздел готов к наполнению контентом</div></section>}

function Profile({name,nickname,setNickname,xp,completed,auth}:{name:string;nickname:string;setNickname:(x:string)=>void;xp:number;completed:number;auth:MewayAuthResult}){const [edit,setEdit]=useState(false);const [draft,setDraft]=useState(nickname);return <><section className="profileHero"><div className="bigAvatar">{name[0]?.toUpperCase()}</div><div><span>УЧЕНИК MEWAY</span><h2>{name}</h2><p>{auth.authenticated?'✓ Discord подключён':'Локальный профиль'}</p></div><button onClick={()=>setEdit(!edit)}>✏️ Изменить профиль</button></section>{edit&&<div className="editBox"><label>Никнейм в MEWAY<input value={draft} onChange={e=>setDraft(e.target.value)}/></label><button onClick={()=>{setNickname(draft.trim()||'Путешественник');setEdit(false)}}>Сохранить</button></div>}<section className="stats"><article><small>⚡ XP</small><b>{xp}</b></article><article><small>🎯 Миссий пройдено</small><b>{completed}</b></article><article><small>🔥 Серия</small><b>4 дня</b></article></section><section className="levelGrid">{levels.map(l=><article className={xp>=l.xp?'unlocked':''} key={l.name}><i>{l.icon}</i><div><b>{l.name}</b><small>{l.xp} XP</small></div><span>{xp>=l.xp?'✓':'🔒'}</span></article>)}</section></>}

function Admin({auth}:{auth:MewayAuthResult}){const [items,setItems]=useState<Mission[]>([]);const [edit,setEdit]=useState<Mission|null>(null);const [loading,setLoading]=useState(true);const headers=useMemo(()=>({Authorization:`Bearer ${auth.accessToken}`,'Content-Type':'application/json'}),[auth.accessToken]);const load=()=>fetch('/api/admin/missions',{headers}).then(r=>r.json()).then(d=>{if(d.ok)setItems(d.missions);setLoading(false)});useEffect(()=>{load()},[]);const blank=():Mission=>({id:0,title:'Новая миссия',description:'',category:'Грамматика',level:'A1',xp:20,icon:'📘',duration:'5 мин',status:'draft',completed:false,tasks:[]});const save=async(m:Mission)=>{await fetch(m.id?`/api/admin/missions/${m.id}`:'/api/admin/missions',{method:m.id?'PUT':'POST',headers,body:JSON.stringify(m)});setEdit(null);load()};const del=async(id:number)=>{if(!confirm('Удалить эту миссию?'))return;await fetch(`/api/admin/missions/${id}`,{method:'DELETE',headers});load()};return <><div className="adminHero"><div><span>🔐 DISCORD VERIFIED ADMIN</span><h2>Центр управления MEWAY</h2><p>Создавай и публикуй учебный контент без изменения кода.</p></div><button onClick={()=>setEdit(blank())}>＋ Новая миссия</button></div><section className="adminStats"><article><b>{items.length}</b><small>Всего миссий</small></article><article><b>{items.filter(x=>x.status==='published').length}</b><small>Опубликовано</small></article><article><b>{items.reduce((a,x)=>a+x.tasks.length,0)}</b><small>Вопросов</small></article></section>{loading?<div className="notice">Загружаем контент…</div>:<section className="adminList"><div className="adminListHead"><b>Миссии</b><span>Статус · уровень · задания · управление</span></div>{items.map(m=><article key={m.id}><div className="missionIcon">{m.icon}</div><div className="adminName"><b>{m.title}</b><small>{m.category} · {m.level} · {m.tasks.length} заданий · +{m.xp} XP</small></div><span className={`status ${m.status}`}>{m.status==='published'?'Опубликовано':m.status==='archived'?'Архив':'Черновик'}</span><button onClick={()=>setEdit(m)}>Изменить</button><button className="danger" onClick={()=>del(m.id)}>Удалить</button></article>)}</section>}{edit&&<MissionEditor mission={edit} onClose={()=>setEdit(null)} onSave={save}/>}</>}

function MissionEditor({mission,onClose,onSave}:{mission:Mission;onClose:()=>void;onSave:(m:Mission)=>void}){const [m,setM]=useState<Mission>(JSON.parse(JSON.stringify(mission)));const patch=(k:keyof Mission,v:unknown)=>setM({...m,[k]:v});const addTask=()=>patch('tasks',[...m.tasks,{id:Date.now(),question:'',options:['','','',''],correctAnswer:'',explanation:''}]);return <div className="modal"><div className="editor"><header><div><span>РЕДАКТОР КОНТЕНТА</span><h2>{m.id?'Редактировать миссию':'Новая миссия'}</h2></div><button onClick={onClose}>×</button></header><div className="formGrid"><label>Название<input value={m.title} onChange={e=>patch('title',e.target.value)}/></label><label>Категория<input value={m.category} onChange={e=>patch('category',e.target.value)}/></label><label>Уровень<select value={m.level} onChange={e=>patch('level',e.target.value as Level)}>{['A1','A2','B1','B2','C1','C2'].map(x=><option key={x}>{x}</option>)}</select></label><label>XP<input type="number" value={m.xp} onChange={e=>patch('xp',Number(e.target.value))}/></label><label>Иконка<input value={m.icon} onChange={e=>patch('icon',e.target.value)}/></label><label>Время<input value={m.duration} onChange={e=>patch('duration',e.target.value)}/></label><label className="wide">Описание<textarea value={m.description} onChange={e=>patch('description',e.target.value)}/></label><label>Статус<select value={m.status} onChange={e=>patch('status',e.target.value)}><option value="draft">Черновик</option><option value="published">Опубликовано</option><option value="archived">Архив</option></select></label></div><div className="taskTitle"><h3>Вопросы ({m.tasks.length})</h3><button onClick={addTask}>＋ Добавить вопрос</button></div>{m.tasks.map((t,idx)=><div className="taskEdit" key={t.id}><div className="taskTop"><b>Вопрос {idx+1}</b><button onClick={()=>patch('tasks',m.tasks.filter((_,i)=>i!==idx))}>Удалить</button></div><input placeholder="Текст вопроса" value={t.question} onChange={e=>{const a=[...m.tasks];a[idx]={...t,question:e.target.value};patch('tasks',a)}}/><div className="optionGrid">{t.options.map((o,oi)=><input key={oi} placeholder={`Вариант ${oi+1}`} value={o} onChange={e=>{const a=[...m.tasks];const opts=[...t.options];opts[oi]=e.target.value;a[idx]={...t,options:opts};patch('tasks',a)}}/>)}</div><input placeholder="Правильный ответ (точно как вариант выше)" value={t.correctAnswer} onChange={e=>{const a=[...m.tasks];a[idx]={...t,correctAnswer:e.target.value};patch('tasks',a)}}/><textarea placeholder="Объяснение ответа" value={t.explanation} onChange={e=>{const a=[...m.tasks];a[idx]={...t,explanation:e.target.value};patch('tasks',a)}}/></div>)}<footer><button className="ghost" onClick={onClose}>Отмена</button><button className="primary" onClick={()=>onSave(m)}>Сохранить миссию</button></footer></div></div>}

export default App
